### ISSUE TITLE
Support for GraalVMs native-image

### ISSUE THREAD

**Issue by choubuzhaole** [apache/shiro#1243]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Hi！

Oracle has created the [GraalVM](https://www.graalvm.org/) and one of its features is the [native-image](https://www.graalvm.org/22.2/docs/getting-started/#native-image) tool, which allows compiling a JVM application into a native executable. This executable doesn't need a JVM to run, it starts faster and often consumes less memory. But this has downsides, as some dynamic features from Java are not supported without additional configuration. The biggest contenders are [reflection](https://www.graalvm.org/22.2/reference-manual/native-image/dynamic-features/Reflection/), [resources](https://www.graalvm.org/22.2/reference-manual/native-image/dynamic-features/Resources/) and [proxies](https://www.graalvm.org/22.2/reference-manual/native-image/dynamic-features/DynamicProxy/).

Luckily, a library can ship some JSON metadata in the [META-INF/native-image/...](https://www.graalvm.org/22.2/reference-manual/native-image/metadata/) directory which enables those features.

For libraries which don't (or can't) add the metadata in their JARs, Oracle has created the [graalvm-reachability-repository](https://github.com/oracle/graalvm-reachability-metadata), which contains this metadata outside of the libraries JAR file. In an ideal world, all of the metadata is moved into the JARs of the libraries, but until our world has reached its ideal state, this repository will be used.

 We are hardly waiting for GrallVM native-image support in officially Shiro repository.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lprimak** [comment]
A PR would be welcome!

**Comment by fpapon** [comment]
@choubuzhaole I cannot see any reference to Apache Shiro in the graalvm-reachibility-metadata repository. Are sure that there is some Apache Shiro related content?

**Comment by choubuzhaole** [comment]
> 的


Hello, my description is wrong, there is indeed no reference to apache shiro in graalvm-reachability-repository. That’s why it asks whether it supports graalvm

**Comment by choubuzhaole** [comment]
Currently I'm trying to use graalvm to compile my project into an executable
### version
graalvm: graalvm-community-jdk-21.0.1
spring-boot:3.2.0
shiro:1.11.0

It compiles fine and when I launch the executable I get the following problem

```
org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:610)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)
	at com.nis.AdminApplication.main(AdminApplication.java:32)
	at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:501)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:218)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
	... 9 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilter': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:188)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:124)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1810)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1277)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:210)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:173)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:168)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAdaptableBeans(ServletContextInitializerBeans.java:153)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:266)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:240)
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:52)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4850)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base@21.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base@21.0.1/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base@21.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base@21.0.1/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:488)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	... 14 common frames omitted
Caused by: org.apache.shiro.util.InstantiationException: Unable to instantiate class [org.apache.shiro.web.filter.authz.HttpMethodPermissionFilter]
	at org.apache.shiro.util.ClassUtils.newInstance(ClassUtils.java:208)
	at org.apache.shiro.web.filter.mgt.DefaultFilter.newInstance(DefaultFilter.java:62)
	at org.apache.shiro.web.filter.mgt.DefaultFilterChainManager.addDefaultFilters(DefaultFilterChainManager.java:382)
	at org.apache.shiro.web.filter.mgt.DefaultFilterChainManager.<init>(DefaultFilterChainManager.java:65)
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.createFilterChainManager(ShiroFilterFactoryBean.java:407)
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.createInstance(ShiroFilterFactoryBean.java:482)
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.getObject(ShiroFilterFactoryBean.java:382)
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.getObject(ShiroFilterFactoryBean.java:122)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:182)
	... 51 common frames omitted
Caused by: java.lang.InstantiationException: org.apache.shiro.web.filter.authz.HttpMethodPermissionFilter
	at java.base@21.0.1/java.lang.Class.newInstance(DynamicHub.java:719)
	at org.apache.shiro.util.ClassUtils.newInstance(ClassUtils.java:206)
	... 59 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.apache.shiro.web.filter.authz.HttpMethodPermissionFilter.<init>()
	at java.base@21.0.1/java.lang.Class.checkMethod(DynamicHub.java:1065)
	at java.base@21.0.1/java.lang.Class.getConstructor0(DynamicHub.java:1228)
	at java.base@21.0.1/java.lang.Class.newInstance(DynamicHub.java:706)
	... 60 common frames omitted

```

**Comment by 8502596** [comment]
In fact, it is divided into two parts. The first is proce-aot, and the second is generating exe
Unfortunately, I couldn't get through the first part.

Modified several configuration issues.  I got the following questions [#45285](https://github.com/spring-projects/spring-boot/issues/45285#issue-3019212208)

I usually use [Ruoyi](https://github.com/yangzongzhuan/RuoYi). About  shiro  He has integrated many configurations.

![Image](https://github.com/user-attachments/assets/94d37d40-6ccd-4b57-8cdf-dfb8504ff756)

so, Making shiro support AOT is a big project and difficult to debug.

For example, if I modified the configuration shiroConfig and did not use AOT to package the exe, it could run normally but got stuck in the pass hot stage. I had to determine which bean caused the process hot to wait indefinitely for preliminary judgment. In fact, I debugged the code SpringApplicability AotProcessor and it has already processed it, but it still doesn't end.
In fact, using shiro2.0.4+ruoyi+spring boot parent 3.4.5 (latest) will result in the following error:


myBatisMapperFactoryBeanPostProcessor defined in class path resource [com/chengsms/framework/config/MyBatisNativeConfiguration.class]
↓
authorizationAttributeSourceAdvisor defined in class path resource [com/chengsms/framework/config/ShiroConfig.class]
┌─────┐
|  securityManager defined in class path resource [com/chengsms/framework/config/ShiroConfig.class]
↑     ↓
|  userRealm defined in class path resource [com/chengsms/framework/config/ShiroConfig.class]
↑     ↓
|   shiroFilterFactoryBean defined in class path resource [com/chengsms/framework/config/ShiroConfig.class]
└─────┘
And MyBatisNativeConfiguration is a necessary native configuration principle online. I don't know how it works, so I modified shiroConfig
It's too difficult for me to make Shiro error free but unable to process oot through the Spring Boot plugin
Tutorial or temporary solution?
