### ISSUE TITLE
[Question] Having trouble with Jakarta EE and Shiro

### ISSUE THREAD

**Issue by whikloj** [apache/shiro#1339]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

I am trying to update code for [Fedora Commons](https://github.com/fcrepo/fcrepo/tree/feature/fcrepo7) from Java 11 to Java 17 and make the switch to Jakarta EE at the same time. I am mostly there (I think) but have struck against an issue when loading the Shiro Filter we run in front of our Jersey system. 

Ours is a little odd in that we do not integrate Shiro to the application, the authz is separate.

When loading a ShiroFilter in our integration tests I had to first include `javax.servlet-api` or I hit `java.lang.NoClassDefFoundError` errors looking for `javax.servlet.Filter`. 

After adding that dependency I now hit this error constructing the bean.

```
java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilter': FactoryBean threw exception on object creation
	at org.glassfish.grizzly.servlet.WebappContext.initFilters(WebappContext.java:1835)
	at org.glassfish.grizzly.servlet.WebappContext.deploy(WebappContext.java:279)
	at org.fcrepo.http.commons.test.util.ContainerWrapper.start(ContainerWrapper.java:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:221)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:110)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:212)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:130)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:142)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:98)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:260)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:163)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$10(ClassBasedTestDescriptor.java:378)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:383)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$11(ClassBasedTestDescriptor.java:378)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:377)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$6(ClassBasedTestDescriptor.java:290)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:279)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:278)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:106)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:105)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilter': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:188)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:124)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1818)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1237)
	at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:332)
	at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:240)
	at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:237)
	at org.glassfish.grizzly.servlet.WebappContext.initFilters(WebappContext.java:1829)
	... 98 more
Caused by: java.lang.ClassCastException: class org.apache.shiro.web.filter.authc.AnonymousFilter cannot be cast to class jakarta.servlet.Filter (org.apache.shiro.web.filter.authc.AnonymousFilter and jakarta.servlet.Filter are in unnamed module of loader 'app')
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.createFilterChainManager(ShiroFilterFactoryBean.java:414)
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.createInstance(ShiroFilterFactoryBean.java:487)
	at org.apache.shiro.spring.web.ShiroFilterFactoryBean.getObject(ShiroFilterFactoryBean.java:386)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:182)
	... 108 more
```

I am not well versed in the masking done with the jakarta classifier, but even with the jakarta classifier it still seems like I am creating a `javax.servlet.Filter` because the AnonymousFilter eventually extends the AbstractFilter which extends `javax.servlet.Filter`.

I apologize as this was setup by someone else so it is possible there is a simple solution, and if so I would appreciate the help switching it over.

The beans are loaded from [here](https://github.com/fcrepo/fcrepo/blob/feature/fcrepo7/fcrepo-auth-common/src/test/resources/spring-test/fcrepo-config.xml) for the integration tests.

I have looked at other jakarta issues in here, most solutions are just to ensure you are using the `<classifier>jakarta</classifier>`. Which I am doing. 

Am I missing something obvious here or are we using Shiro in a non-standard way or are we needing to continue using `javax.servlet.Filter` to use Shiro?

cheers!

**Comment by fpapon** [comment]
@whikloj I think that you need to import the Shiro bom to auto manage the non jakarta Shiro modules exclusion.
You can find an example here:
https://github.com/apache/shiro/blob/main/samples/web-jakarta/pom.xml

To be sure that you don't have non jakarta module, you can check your generated artifacts.

**Comment by whikloj** [comment]
Hi @fpapon,

I'm not sure I am understanding the use of the bom. 

If in my main project pom I define (where `${shiro.version}` ==`2.0.0`):
```xml
<dependencyManagement>
      <dependency>
        <groupId>org.apache.shiro</groupId>
        <artifactId>shiro-core</artifactId>
        <version>${shiro.version}</version>
        <classifier>jakarta</classifier>
      </dependency>
      <dependency>
        <groupId>org.apache.shiro</groupId>
        <artifactId>shiro-spring</artifactId>
        <version>${shiro.version}</version>
        <classifier>jakarta</classifier>
      </dependency>
      <dependency>
        <groupId>org.apache.shiro</groupId>
        <artifactId>shiro-web</artifactId>
        <version>${shiro.version}</version>
        <classifier>jakarta</classifier>
      </dependency>
      <dependency>
        <groupId>org.apache.shiro</groupId>
        <artifactId>shiro-bom</artifactId>
        <version>${shiro.version}</version>
        <type>pom</type>
      </dependency>
</dependencyManagement>
```
and in the actual auth module I add dependencies on:
```xml
   <dependency>
      <groupId>org.apache.shiro</groupId>
      <artifactId>shiro-spring</artifactId>
      <classifier>jakarta</classifier>
    </dependency>
    <dependency>
      <groupId>org.apache.shiro</groupId>
      <artifactId>shiro-web</artifactId>
      <classifier>jakarta</classifier>
    </dependency>
```

Building the auth module, I end up with
```
Dependency convergence error for javax.servlet.jsp:jsp-api:jar:2.2:provided paths to dependency are:
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-javax.servlet.jsp:jsp-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-javax.servlet.jsp:jsp-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-spec:jar:1.2.5:provided
      +-javax.servlet.jsp:jsp-api:jar:2.1:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-impl:jar:1.2.5:provided
      +-javax.servlet.jsp:jsp-api:jar:2.1:provided

[WARNING] 
Dependency convergence error for javax.el:el-api:jar:2.2:provided paths to dependency are:
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-javax.servlet.jsp:jsp-api:jar:2.2:provided
      +-javax.el:el-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-spec:jar:1.2.5:provided
      +-javax.el:el-api:jar:1.0:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-impl:jar:1.2.5:provided
      +-javax.el:el-api:jar:1.0:provided
```

Previously I had `shiro-core` and `shiro-spring` as dependencies, so if I switch back to those and remove `shiro-web` I end up in the same spot via `shiro-spring`

```
Dependency convergence error for javax.servlet.jsp:jsp-api:jar:2.2:provided paths to dependency are:
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-javax.servlet.jsp:jsp-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-org.apache.taglibs:taglibs-standard-spec:jar:1.2.5:provided
        +-javax.servlet.jsp:jsp-api:jar:2.1:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-org.apache.taglibs:taglibs-standard-impl:jar:1.2.5:provided
        +-javax.servlet.jsp:jsp-api:jar:2.1:provided

[WARNING] 
Dependency convergence error for javax.el:el-api:jar:2.2:provided paths to dependency are:
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-javax.servlet.jsp:jsp-api:jar:2.2:provided
        +-javax.el:el-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-org.apache.taglibs:taglibs-standard-spec:jar:1.2.5:provided
        +-javax.el:el-api:jar:1.0:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-spring:jar:jakarta:2.0.0:compile
    +-org.apache.shiro:shiro-web:jar:2.0.0:compile
      +-org.apache.taglibs:taglibs-standard-impl:jar:1.2.5:provided
        +-javax.el:el-api:jar:1.0:provided
```

Which seems to say that the library has a dependency convergence error with itself. So I am sure I am missing something.

**Comment by lprimak** [comment]
Looks like you are not using the BOM as @fpapon already said. You need to use the BOM to fix your issue:
As describer here: https://shiro.apache.org/jakarta-ee.html
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-bom</artifactId>
            <version>2.0.0</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by whikloj** [comment]
Hey @lprimak 

Sorry that I didn't push up my changes. I have updated the working branch. 

I use the `<dependencyManagement>` in my root pom to define the versions of [`shiro-spring`, `shiro-core`, `shiro-web` and `shiro-bom`](https://github.com/fcrepo/fcrepo/blob/feature/fcrepo7/pom.xml#L604-L628), then in the authz module (`fcrepo-auth-common`) I define [those as dependencies](https://github.com/fcrepo/fcrepo/blob/feature/fcrepo7/fcrepo-auth-common/pom.xml#L45-L59) but also define [`shiro-bom`](https://github.com/fcrepo/fcrepo/blob/feature/fcrepo7/fcrepo-auth-common/pom.xml#L220-L230) in a `<dependencyManagement>` element?

Does that seem correct, because I am still hitting dependency convergence errors within shiro.
```
Dependency convergence error for javax.el:el-api:jar:2.2:provided paths to dependency are:
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-javax.servlet.jsp:jsp-api:jar:2.2:provided
      +-javax.el:el-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-spec:jar:1.2.5:provided
      +-javax.el:el-api:jar:1.0:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-impl:jar:1.2.5:provided
      +-javax.el:el-api:jar:1.0:provided
```

**Comment by lprimak** [comment]
Can you print out output of `mvn dependency:tree`?
You should not have any `javax.*` dependencies at all

**Comment by fpapon** [comment]
@whikloj If you share a git branch may be I can try to fix it.
Side note about the bom, you need to set the dependency scope to `import`.

**Comment by whikloj** [comment]
I've played around but I'm not really making any head way. I have removed all dependencies from the root pom.xml _except_ the `shiro-bom`. 
```xml
<dependencyManagement>
  <dependency>
    <groupId>org.apache.shiro</groupId>
    <artifactId>shiro-bom</artifactId>
    <version>${shiro.version}</version>
    <scope>import</scope>
    <type>pom</type>
  </dependency>
</dependencyManagement>
```

Then in the `fcrepo-auth-common` I have gone back to the original dependencies of
```xml
<dependency>
  <groupId>org.apache.shiro</groupId>
  <artifactId>shiro-core</artifactId>
  <classifier>jakarta</classifier>
</dependency>
<dependency>
  <groupId>org.apache.shiro</groupId>
  <artifactId>shiro-web</artifactId>
  <classifier>jakarta</classifier>
</dependency>
```

But it stills seems to have some transitive dependency.
```
[INFO] -------------------< org.fcrepo:fcrepo-auth-common >--------------------
[INFO] Building Fedora Repository Authorization Commons Module 6.5.0-SNAPSHOT [16/22]
[INFO]   from fcrepo-auth-common/pom.xml
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- clean:3.1.0:clean (default-clean) @ fcrepo-auth-common ---
[INFO] 
[INFO] --- enforcer:3.0.0:enforce (default) @ fcrepo-auth-common ---
[WARNING] 
Dependency convergence error for javax.el:el-api:jar:2.2:provided paths to dependency are:
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-javax.servlet.jsp:jsp-api:jar:2.2:provided
      +-javax.el:el-api:jar:2.2:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-spec:jar:1.2.5:provided
      +-javax.el:el-api:jar:1.0:provided
and
+-org.fcrepo:fcrepo-auth-common:bundle:6.5.0-SNAPSHOT
  +-org.apache.shiro:shiro-web:jar:jakarta:2.0.0:compile
    +-org.apache.taglibs:taglibs-standard-impl:jar:1.2.5:provided
      +-javax.el:el-api:jar:1.0:provided

[WARNING] Rule 2: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Fedora Commons 6.5.0-SNAPSHOT:
[INFO] 
[INFO] Fedora Commons :: Parent POM ....................... SUCCESS [  0.512 s]
[INFO] Fedora Commons ..................................... SUCCESS [  3.861 s]
[INFO] Fedora Repository Common Module .................... SUCCESS [  2.701 s]
[INFO] Fedora Repository Configurations Module ............ SUCCESS [  2.273 s]
[INFO] Fedora Repository Kernel API ....................... SUCCESS [  7.252 s]
[INFO] Fedora Repository Persistence API Module ........... SUCCESS [  1.214 s]
[INFO] Fedora Repository Persistence Common Module ........ SUCCESS [  2.719 s]
[INFO] Fedora Repository Search API ....................... SUCCESS [  1.289 s]
[INFO] Fedora Repository Kernel Implementation ............ SUCCESS [ 20.730 s]
[INFO] Fedora Repository OCFL Persistence Impl ............ SUCCESS [ 15.147 s]
[INFO] Fedora Repository Statistics API ................... SUCCESS [  1.197 s]
[INFO] Fedora Repository Search Impl ...................... SUCCESS [  2.720 s]
[INFO] Fedora Repository HTTP Commons Module .............. SUCCESS [  8.214 s]
[INFO] Fedora Event Serialization ......................... SUCCESS [  5.814 s]
[INFO] Fedora Repository JMS Module ....................... SUCCESS [ 51.959 s]
[INFO] Fedora Repository Authorization Commons Module ..... FAILURE [  0.227 s]
[INFO] Fedora Repository Stats Impl ....................... SKIPPED
[INFO] Fedora Repository HTTP API Module .................. SKIPPED
[INFO] Fedora Repository WebAC Authorization Module ....... SKIPPED
[INFO] Fedora Repository Deployable Web Application ....... SKIPPED
[INFO] Fedora Repository LDP integration tests Module ..... SKIPPED
[INFO] Fedora Repository RDF integration tests Module ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:09 min
[INFO] Finished at: 2024-03-04T16:02:47-06:00
[INFO] ------------------------------------------------------------------------
```

Could it be our `enforcer` plugin configuration? I looked at it but I couldn't really see why this would occur. 🤷

**Comment by lprimak** [comment]
Can you try disabling enforcer plugin and see if that works?

**Comment by lprimak** [comment]
Also you may want to try with the latest maven and with all up-to-date plugins as yours are out of date

**Comment by whikloj** [comment]
I updated most of the plugins and am still working my way through some issues from that, but I am not seeing the original problem. So I guess it was an issue with the maven-enforcer-plugin or perhaps the maven-compiler-plugin. 

Either way, thank you for your help. I think this is closed.

**Comment by lprimak** [comment]
Glad it worked out!
