### ISSUE TITLE
[Question] Question title springboot3.x FormAuthenticationFilter  还是引入的 javax 的包

### ISSUE THREAD

**Issue by sunxingxiang** [apache/shiro#1866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

2.0.1v + springboot3.x FormAuthenticationFilter  还是引入的 javax 的包

**Comment by lprimak** [comment]
Have you looked at https://github.com/apache/shiro/tree/main/samples/spring-boot-3-web example?
Specifically, how the Shiro BOM is included?

That sample specifically shows how to use Spring Boot 3 with Shiro.

**Comment by sunxingxiang** [comment]
> Have you looked at https://github.com/apache/shiro/tree/main/samples/spring-boot-3-web example? Specifically, how the Shiro BOM is included?
> 
> That sample specifically shows how to use Spring Boot 3 with Shiro.

i run the example but error 
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.1.13.jar:6.1.13]
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	... 37 common frames omitted

**Comment by fpapon** [comment]
You need to use the jakarta classifier and use the BOM to exclude the non jakarta dependencies.
